name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: early
    - run: |
        if [ "${{ steps.early.outputs.bumped }}" == "true" ]; then
          echo "committing ${{ steps.early.outputs.new-version }}:"
          echo "${{ steps.early.outputs.changed-files }}"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "${{ steps.early.outputs.new-version }}"
          git tag -a "v${{ steps.early.outputs.new-version }}" -m "${{ steps.early.outputs.new-version }}"
        fi
    - uses: ./
      id: nothing
    - run: |
        if [ "${{ steps.nothing.outputs.bumped }}" == "true" ]; then
          echo "unexpectedly bumped"
          exit 1
        fi
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        echo "test" > test
        git add test
        git commit -m "feat: Add test"
    - uses: ./
      id: bumping
      with:
        bump-files: v.ini
    - run: |
        if [ "${{ steps.bumping.outputs.bumped }}" == "true" ]; then
          if [ "${{ steps.bumping.outputs.new-version }}" != "" ]; then
            echo "bumped to version ${{ steps.bumping.outputs.new-version }}"
          else
            echo "the new version is missing"
            exit 1
          fi
          if [ "${{ steps.bumping.outputs.changed-files }}" != "" ]; then
            echo "modified:"
            echo "${{ steps.bumping.outputs.changed-files }}"
          else
            echo "not modified changelog"
            exit 1
          fi
        else
          echo "not bumped to a new version"
          exit 1
        fi

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: early
    - run: |
        if [ "${{ steps.early.outputs.bumped }}" == "true" ]; then
          echo "committing ${{ steps.early.outputs.new-version }}:"
          echo "${{ steps.early.outputs.changed-files }}"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "${{ steps.early.outputs.new-version }}"
          git tag -a "v${{ steps.early.outputs.new-version }}" -m "${{ steps.early.outputs.new-version }}"
        fi
    - uses: ./
      id: nothing
    - run: |
        if [ "${{ steps.nothing.outputs.bumped }}" == "true" ]; then
          echo "unexpectedly bumped"
          exit 1
        fi
    - run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        echo "test" > test
        git add test
        git commit -m "feat: Add test"
    - uses: ./
      id: bumping
      with:
        bump-files: v.ini
    - run: |
        if [ "${{ steps.bumping.outputs.bumped }}" == "true" ]; then
          if [ "${{ steps.bumping.outputs.new-version }}" != "" ]; then
            echo "bumped to version ${{ steps.bumping.outputs.new-version }}"
          else
            echo "the new version is missing"
            exit 1
          fi
          if [ "${{ steps.bumping.outputs.changed-files }}" != "" ]; then
            echo "modified:"
            echo "${{ steps.bumping.outputs.changed-files }}"
          else
            echo "not modified changelog"
            exit 1
          fi
        else
          echo "not bumped to a new version"
          exit 1
        fi

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: ./
  #     id: early
  #   - run: |
  #       if [ "${{ steps.early.outputs.bumped }}" == "true" ]; then
  #         echo "committing ${{ steps.early.outputs.new-version }}:"
  #         echo "${{ steps.early.outputs.changed-files }}"
  #         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
  #         git config --global user.name "github-actions[bot]"
  #         git commit -am "${{ steps.early.outputs.new-version }}"
  #         git tag -a "v${{ steps.early.outputs.new-version }}" -m "${{ steps.early.outputs.new-version }}"
  #       fi
  #   - id: nothing
  #     uses: ./
  #   - run: |
  #       if [ "${{ steps.nothing.outputs.bumped }}" == "true" ]; then
  #         echo "unexpectedly bumped"
  #         exit 1
  #       fi
  #   - run: |
  #       git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
  #       git config --global user.name "github-actions[bot]"
  #       echo "test" > test
  #       git add test
  #       git commit -m "feat: Add test"
  #   - uses: ./
  #     id: bumping
  #     with:
  #       bump-files: v.ini
  #   - run: |
  #       if [ "${{ steps.bumping.outputs.bumped }}" == "true" ]; then
  #         if [ "${{ steps.bumping.outputs.new-version }}" != "" ]; then
  #           echo "bumped to version ${{ steps.bumping.outputs.new-version }}"
  #         else
  #           echo "the new version is missing"
  #           exit 1
  #         fi
  #         if [ "${{ steps.bumping.outputs.changed-files }}" != "" ]; then
  #           echo "modified:"
  #           echo "${{ steps.bumping.outputs.changed-files }}"
  #         else
  #           echo "not modified changelog"
  #           exit 1
  #         fi
  #       else
  #         echo "not bumped to a new version"
  #         exit 1
  #       fi

  release:
    if: ${{ github.ref_name == 'master' }}
    needs:
      - linux
      - macos
      # - windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/publish-release-action@v1
      with:
        no-bump: true
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
